# Integrate Training Data

In [4]:
import scanpy as sc

In [ ]:
# Extract data from one sample
mouse_liver_one_sample = (
    "../data/training_data/GSM5764262_filtered_feature_bc_matrix_CS14.h5"
)

In [ ]:
adata = sc.read_10x_h5(mouse_liver_one_sample)

/home/ubuntu/software/miniforge3/envs/liver-sc-imputation/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/ubuntu/software/miniforge3/envs/liver-sc-imputation/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [9]:
adata

AnnData object with n_obs × n_vars = 5106 × 31053
    var: 'gene_ids', 'feature_types', 'genome'

In [11]:
adata.var["gene_ids"]

Xkr4              ENSMUSG00000051951
Gm1992            ENSMUSG00000089699
Gm37381           ENSMUSG00000102343
Rp1               ENSMUSG00000025900
Sox17             ENSMUSG00000025902
                         ...
AC168977.1        ENSMUSG00000079808
AC149090.1        ENSMUSG00000095041
CAAA01118383.1    ENSMUSG00000063897
Vmn2r122          ENSMUSG00000096730
CAAA01147332.1    ENSMUSG00000095742
Name: gene_ids, Length: 31053, dtype: object

In [12]:
# CellRanger liver data
# Apparently countTable_mouseStSt holds data with all cells

mouse_liver_all_samples = "../data/training_data/countTable_mouseStSt"

In [13]:
adata = sc.read_10x_mtx(mouse_liver_all_samples)

:

In [1]:
import anndata as ad
import pandas as pd

In [15]:
adata = ad.read_h5ad(
    "../data/training_data/mouse_liver_scRNAseq_healthy.h5ad", backed=True
)
adata

AnnData object with n_obs × n_vars = 389056 × 31053 backed at '../data/training_data/mouse_liver_scRNAseq_healthy.h5ad'

In [21]:
obs = pd.read_csv("../data/training_data/countTable_mouseStSt/annot_mouseStStAll.csv")
obs

,UMAP_1,UMAP_2,cluster,annot,sample,cell,digest,typeSample
0,10.199693,-7.500118,21,T cells,CISE12,AAACCTGAGTTCGCGC-1,exVivo,citeSeq
1,12.429611,-5.372781,11,T cells,CISE12,AAACCTGGTGAGGCTA-1,exVivo,citeSeq
2,14.550602,-2.247851,26,ILC1s,CISE12,AAACCTGTCGGTGTCG-1,exVivo,citeSeq
3,11.260082,-5.692209,11,T cells,CISE12,AAACGGGAGTACGCGA-1,exVivo,citeSeq
4,13.879457,-1.479918,26,ILC1s,CISE12,AAACGGGCAGTATGCT-1,exVivo,citeSeq
...,...,...,...,...,...,...,...,...
185889,7.300422,-5.189817,19,Neutrophils,CS16,TTCTTAGCACATAACC-46,exVivo,scRnaSeq
185890,5.629435,-6.119583,19,Neutrophils,CS16,TTGAACGAGTGAAGTT-46,exVivo,scRnaSeq
185891,6.191045,-5.096178,19,Neutrophils,CS16,TTGACTTTCCAATGGT-46,exVivo,scRnaSeq
185892,6.637616,-5.062717,19,Neutrophils,CS16,TTGTAGGTCACTCCTG-46,exVivo,scRnaSeq
185893,7.274597,-5.612700,19,Neutrophils,CS16,TTTCCTCTCAGCATGT-46,exVivo,scRnaSeq

In [17]:
adata.obs_names

Index(['AAACCTGAGAGCCCAA-1', 'AAACCTGAGCTAGTCT-1', 'AAACCTGAGTTCGCGC-1',
       'AAACCTGCAACACCCG-1', 'AAACCTGCATAGGATA-1', 'AAACCTGCATTGCGGC-1',
       'AAACCTGGTATGAATG-1', 'AAACCTGGTCAGTGGA-1', 'AAACCTGGTGAGGCTA-1',
       'AAACCTGTCGGTGTCG-1',
       ...
       'TTTGTCACATGCAACT-46', 'TTTGTCAGTAACGTTC-46', 'TTTGTCAGTATTACCG-46',
       'TTTGTCAGTCCAGTGC-46', 'TTTGTCAGTGAGGGAG-46', 'TTTGTCAGTTGATTGC-46',
       'TTTGTCATCAACACAC-46', 'TTTGTCATCCCACTTG-46', 'TTTGTCATCGCGCCAA-46',
       'TTTGTCATCGGAATCT-46'],
      dtype='object', length=389056)

In [23]:
obs = obs.set_index("cell")
obs

,UMAP_1,UMAP_2,cluster,annot,sample,digest,typeSample
cell,,,,,,,
AAACCTGAGTTCGCGC-1,10.199693,-7.500118,21,T cells,CISE12,exVivo,citeSeq
AAACCTGGTGAGGCTA-1,12.429611,-5.372781,11,T cells,CISE12,exVivo,citeSeq
AAACCTGTCGGTGTCG-1,14.550602,-2.247851,26,ILC1s,CISE12,exVivo,citeSeq
AAACGGGAGTACGCGA-1,11.260082,-5.692209,11,T cells,CISE12,exVivo,citeSeq
AAACGGGCAGTATGCT-1,13.879457,-1.479918,26,ILC1s,CISE12,exVivo,citeSeq
...,...,...,...,...,...,...,...
TTCTTAGCACATAACC-46,7.300422,-5.189817,19,Neutrophils,CS16,exVivo,scRnaSeq
TTGAACGAGTGAAGTT-46,5.629435,-6.119583,19,Neutrophils,CS16,exVivo,scRnaSeq
TTGACTTTCCAATGGT-46,6.191045,-5.096178,19,Neutrophils,CS16,exVivo,scRnaSeq
TTGTAGGTCACTCCTG-46,6.637616,-5.062717,19,Neutrophils,CS16,exVivo,scRnaSeq
TTTCCTCTCAGCATGT-46,7.274597,-5.612700,19,Neutrophils,CS16,exVivo,scRnaSeq

In [24]:
obs = obs.reindex(adata.obs_names)
obs

,UMAP_1,UMAP_2,cluster,annot,sample,digest,typeSample
AAACCTGAGAGCCCAA-1,0.545411,-8.261642,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGAGCTAGTCT-1,-6.840581,3.870898,0.0,Kupffer cells,CISE12,exVivo,citeSeq
AAACCTGAGTTCGCGC-1,10.199693,-7.500118,21.0,T cells,CISE12,exVivo,citeSeq
AAACCTGCAACACCCG-1,0.935696,-8.487344,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGCATAGGATA-1,6.846276,3.955263,37.0,Monocytes & Monocyte-derived cells,CISE12,exVivo,citeSeq
...,...,...,...,...,...,...,...
TTTGTCAGTTGATTGC-46,4.033401,2.078562,16.0,cDC2s,CS16,exVivo,scRnaSeq
TTTGTCATCAACACAC-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTCATCCCACTTG-46,3.694207,3.234744,16.0,cDC2s,CS16,exVivo,scRnaSeq
TTTGTCATCGCGCCAA-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTCATCGGAATCT-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The gene-cell count matrices contain all genes and all cells before any quality control filtering was done.
The cell annotation matrices contain the cells that were retained after QC filtering.

In [25]:
obs.dropna()

,UMAP_1,UMAP_2,cluster,annot,sample,digest,typeSample
AAACCTGAGAGCCCAA-1,0.545411,-8.261642,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGAGCTAGTCT-1,-6.840581,3.870898,0.0,Kupffer cells,CISE12,exVivo,citeSeq
AAACCTGAGTTCGCGC-1,10.199693,-7.500118,21.0,T cells,CISE12,exVivo,citeSeq
AAACCTGCAACACCCG-1,0.935696,-8.487344,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGCATAGGATA-1,6.846276,3.955263,37.0,Monocytes & Monocyte-derived cells,CISE12,exVivo,citeSeq
...,...,...,...,...,...,...,...
TTTGGTTGTCAGAATA-46,-4.068020,-2.775618,12.0,cDC1s,CS16,exVivo,scRnaSeq
TTTGTCAAGAAAGTGG-46,-4.503767,-2.667650,12.0,cDC1s,CS16,exVivo,scRnaSeq
TTTGTCACAGTATGCT-46,-3.729786,-1.951574,12.0,cDC1s,CS16,exVivo,scRnaSeq
TTTGTCAGTTGATTGC-46,4.033401,2.078562,16.0,cDC2s,CS16,exVivo,scRnaSeq
TTTGTCATCCCACTTG-46,3.694207,3.234744,16.0,cDC2s,CS16,exVivo,scRnaSeq

This only keeps the cells that are retained after QC.

In [26]:
adata.obs = obs
adata.obs

,UMAP_1,UMAP_2,cluster,annot,sample,digest,typeSample
AAACCTGAGAGCCCAA-1,0.545411,-8.261642,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGAGCTAGTCT-1,-6.840581,3.870898,0.0,Kupffer cells,CISE12,exVivo,citeSeq
AAACCTGAGTTCGCGC-1,10.199693,-7.500118,21.0,T cells,CISE12,exVivo,citeSeq
AAACCTGCAACACCCG-1,0.935696,-8.487344,9.0,pDCs,CISE12,exVivo,citeSeq
AAACCTGCATAGGATA-1,6.846276,3.955263,37.0,Monocytes & Monocyte-derived cells,CISE12,exVivo,citeSeq
...,...,...,...,...,...,...,...
TTTGTCAGTTGATTGC-46,4.033401,2.078562,16.0,cDC2s,CS16,exVivo,scRnaSeq
TTTGTCATCAACACAC-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTCATCCCACTTG-46,3.694207,3.234744,16.0,cDC2s,CS16,exVivo,scRnaSeq
TTTGTCATCGCGCCAA-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTCATCGGAATCT-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Create a boolean mask: True if NOT all values in .obs are NaN for that row
valid_obs_mask = ~adata.obs.isna().all(axis=1)
valid_obs_mask

AAACCTGAGAGCCCAA-1      True
AAACCTGAGCTAGTCT-1      True
AAACCTGAGTTCGCGC-1      True
AAACCTGCAACACCCG-1      True
AAACCTGCATAGGATA-1      True
                       ...
TTTGTCAGTTGATTGC-46     True
TTTGTCATCAACACAC-46    False
TTTGTCATCCCACTTG-46     True
TTTGTCATCGCGCCAA-46    False
TTTGTCATCGGAATCT-46    False
Length: 389056, dtype: bool

In [29]:
bdata = adata[valid_obs_mask]
bdata

View of AnnData object with n_obs × n_vars = 185894 × 31053 backed at '../data/training_data/mouse_liver_scRNAseq_healthy.h5ad'
    obs: 'UMAP_1', 'UMAP_2', 'cluster', 'annot', 'sample', 'digest', 'typeSample'

Drops all observations that were filtered by the QC.